# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_type', models.CharField(max_length=50)),
                ('href', models.CharField(max_length=300)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(default='album', max_length=20)),
                ('uri', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('href', models.CharField(max_length=300)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(default='artist', max_length=20)),
                ('uri', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('disc_number', models.IntegerField()),
                ('duration_ms', models.IntegerField()),
                ('explicit', models.BooleanField()),
                ('href', models.CharField(max_length=300)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('is_playable', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('preview_url', models.CharField(max_length=200)),
                ('type', models.CharField(default='track', max_length=20)),
                ('uri', models.CharField(max_length=200)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myspotify.Album')),
            ],
        ),
    ]
