# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspotify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='track',
            name='image',
            field=models.CharField(default='', max_length=300),
        ),
    ]
