# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 18:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspotify', '0002_auto_20170223_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='user',
            field=models.ManyToManyField(related_name='albums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artist',
            name='user',
            field=models.ManyToManyField(related_name='artists', to=settings.AUTH_USER_MODEL),
        ),
    ]
