# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspotify', '0003_auto_20170223_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.RemoveField(
            model_name='track',
            name='user',
        ),
        migrations.AddField(
            model_name='artist',
            name='new',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
